# Generated by Django 5.2 on 2026-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee_dob_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
