# Generated by Django 5.2 on 2026-03-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
