# Generated by Django 5.2 on 2026-04-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='emp_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
